### ISSUE TITLE
Openfl 2.1 update don't work

### ISSUE THREAD

**Issue by ViktorLajos** [away3d/away3d-core-openfl#18]
I just updated the lime to 2.0.0, and openfl to 2.1 (http://www.openfl.org/blog/2014/10/14/openfl-2-1/), and it won't work with the away3d. I would try the basic_view project, and I realize that there are many changes: first I try to build the project on the old way: "lime build project.xml"
it says: Error: "project.xml" is an unknown target

after that I tried this command: "lime build project.xml html5"
it says: Error: Could not find haxelib "format", does it need to be installed?

than I commented the line <haxelib name="format" if="html5" /> from project.xml
It seems the good way, but now it give the following error:

C:\HaxeToolkit\haxe\lib\away3d/1,0,4-alpha/backends/html5/openfl/display3D/Conte
xt3D.hx:364: characters 8-26 : Class<lime.graphics.opengl.GL> has no field unifo
rmMatrix3D (Suggestions: uniformMatrix3fv, uniformMatrix4fv, uniformMatrix2fv)

**Comment by justnajm** [comment]
I am having the same issue, even Basic_View is prompting for
    openfl test html5
    Error: Could not find haxelib "format", does it need to be installed?

**Comment by modjke** [comment]
justnajm,
you need to install format haxelib
just run
haxelib install format

**Comment by Greg209** [comment]
You can probably remove the haxelib reference to 'format' from the project.xml file as there used to be dependency issues but now with lime-next those may have gone. I've tried removing it and Basic_View works fine on both neko and html5. 

Please ensure you have the latest OpenFL and Away3D. If you are still having issues please provide as much information as possible - e.g. which platform your are building on, targets, output, etc.

**Comment by justnajm** [comment]
Yes just updating lime, I have recently downloaded your away3d examples. I am using ubuntu 14.04 LTS
Not the right place to ask but which IDE you guys use on linux os

**Comment by Greg209** [comment]
There may still be issues on linux - there is already an issue logged against that #15 which I've not investigated recently. I'm using a Mac and use Sublime Text 2.

**Comment by justnajm** [comment]
Ok I can run Basic_View in html5 and its working, I don't know it its worth mentioning that after complete rotation of base it stuck and restart rotation again, even frames drop to 48 from 60.

Same example showing black screen in flash and neko as you marked #15
