### ISSUE TITLE
Code issue for particle system

### ISSUE THREAD

**Issue by muguangyi** [away3d/away3d-core-openfl#19]
I try to integrate away3d for particle system feature and found the following code issues. I did changes on my side and think I should list them here:
1. ParticleColorNode.hx: 
    ((_usesCycle) ? "sin " : animationRegisterCache.vertexLife.toString()) should change to ((_usesCycle) ? sin : animationRegisterCache.vertexLife), but first need to move "var sin:ShaderRegisterElement" definition out first.
2. ParticleBillboardState.hx:
    #if !flash
        import openfl.geom.Orientation3D;
    #else
        import flash.geom.Orientation3D;
    #end
    could be only leave the openfl definition part.
3. ParticleRotationVelocityState.hx:
    _dynamicPropertiesDirty is ObjectMap type, but there use WeakMap to create. Should change to ObjectMap?
4. ParticleSegmentedColorState.hx:
    _timeLifeData is Array<Float>, so "length" property can't be set, so the last line should be commented out, or change to Vector<Float>?
5. ParticleSpriteSheetState.hx:
    No parameters for Array<Float>, so " _spriteSheetData = new Array<Float>(8, true)" can't work, should change to  _spriteSheetData = new Array<Float>() or use Vector<Float>?

**Comment by Greg209** [comment]
These changes should be in place now.
