### ISSUE TITLE
We should unify html5 and native backend, shouldn't we?

### ISSUE THREAD

**Issue by vroad** [away3d/away3d-core-openfl#20]
My repo also have performance fixes and additions, but I think we should solve this first, as it causes huge changes to the repository structure.

In my opnion we don't have to make them separated. As both native and html5 use OpenGL, they don't have big differences in the implementation. Conditional compilation is enough for this case, isn't it? Otherwise, we'll end up copying the code every time we change the code of one backend.

**Comment by vroad** [comment]
Stage3D staff is now merged with OpenFL, so we should close this issue?

**Comment by Greg209** [comment]
Although the merge is in progress I'm working with Joshua to make sure we are in a situation where things still work whilst providing a more stable Stage3D implementation. Things aren't quite there yet bet we're close
