### ISSUE TITLE
AGLSLShaderUtils error, Windows CPP target

### ISSUE THREAD

**Issue by KirillPoletaev** [away3d/away3d-core-openfl#23]
Getting this error on Windows in FlashDevelop:

```
away3d_openfl/backends/native/openfl/display3D/shaders/AGLSLShaderUtils.hx:39: lines 39-83 : Module openfl.display3D.shaders.Shader does not define type Shader
```

**Comment by Greg209** [comment]
openfl.display3D.* now moved into core OpenFL library. If this error still remains with that latest OpenFL/Lime and Away3D please raise the issue on the OpenFL git repo.
