### ISSUE TITLE
I try using this port with the away3d examples ( in haxe), but always get a blank screen.

### ISSUE THREAD

**Issue by VishwasGagrani** [away3d/away3d-core-openfl#27]
I always get a blank screen, while trying to run the haxe based away3d examples. Tried targetting flash, html5 and windows. But keep getting a blank screen. What can be the issue ? Do i need to install something extra. 

I am having haxetoolkit 3.1.3 , and ran many haxe examples, successfully on flash develop. But the away3d examples show only blank screen.

http://i1256.photobucket.com/albums/ii497/VishwasGagrani/screen_zps739df8c5.png

**Comment by Tiago-Ling** [comment]
What are the versions of your other libraries (Lime and OpenFL)? 

I'm running all demos flawlessly in Flash, Windows, Neko and HTML5.

My library versions:
* Haxe 3.1.3
* OpenFL 2.2.3
* Lime 2.0.6
* Hxcpp 3.1.48

**Comment by VishwasGagrani** [comment]
Hmm, i need to update them then. 

currently it's the following :
haxe 3.1.3
away3d: 1.0.0-alpha 1.0.1-alpha [1.0.4-alpha]
hxcpp: [3.1.39]
lime: [1.0.0]
openfl: 2.0.0 [2.0.1]

**Comment by Tiago-Ling** [comment]
99% sure your problem is with lime.

Just update it and test, the other version differences are not relevant afaik.

**Comment by Greg209** [comment]
Later this evening (in a few hours perhaps) I'll be releasing a new version of Away3D with appropriate updates to the examples which are built to use the latest (or very recent) version of OpenFL & Lime e.g. OpenFL 2.2.4 which includes the migrated Stage3D implementation - so it is removed from this repo into the OpenFL core lib. Expect are release, including haxelib update soon. Might be worth trying again then. I'll post again & close once completed.

**Comment by VishwasGagrani** [comment]
ok, I installed lime, but now get this error : 
http://i1256.photobucket.com/albums/ii497/VishwasGagrani/Untitled_zpsturrijcx.png

It didnot occur previously. Seems to be a result of lime update. 

Vishwas

**Comment by Greg209** [comment]
private static var preloader:; is an error as the ':' should be followed by a type but isn't.

**Comment by VishwasGagrani** [comment]
I understand that, but "ApplicationMain.hx" is automatically generated file. I don't see any such file in the project.

**Comment by VishwasGagrani** [comment]
Oh.. i figured out, this problem occurs when Application.xml doesnot have 3 levels of package naming
so instead of 
<meta title="project" package="project" version="1.0.0" company="Vishwas" />

It should be 
<meta title="project" package="com.project.project" version="1.0.0" company="Vishwas" />


But anyway, i am still getting a blank screen after the build. Updating the libraries too didnot seem to solve the problem.

**Comment by Tiago-Ling** [comment]
Are other samples from other libraries working alright (e.g. OpenFL) ?

This may be a faulty installation of Haxe / OpenFL / Lime - i already installed this version of Away3d in several machines and none of them gave me this error. 

Did you try to run any sample from Away3d directly from the command line (switch to sample root folder and run `lime test <target>` ?

**Comment by Greg209** [comment]
As I mentioned - new versions will be uploaded shortly so might be better to wait until after that. A lot of changes happened to openfl and subsequent changes to away3d have only so far been in the git repo rather than the releases.

**Comment by VishwasGagrani** [comment]
@Tiago-Ling  : Ya, i have tested applications for  flash-player and android with OpenFl, and they work all fine. All of them are installed as usual on C:/HaxeToolkit so not sure about faulty installation.  Actually, never used lime with commandline.. so, will need to check that out.

@Greg209  : Yes, that would be better actually. I hope it will work then.

Thankyou.

**Comment by Greg209** [comment]
Latest versions of the examples and Away3D are now available via haxelib.
