### ISSUE TITLE
Render textures tainted of Green

### ISSUE THREAD

**Issue by MangelMaxime** [away3d/away3d-core-openfl#28]
Hi guys, when I try to render my basic view under another target than Flash i get all my textures tainted of green. It's happening even with the samples source code.

![Image](http://puu.sh/dT063/b9a46c315c.jpg)

Should I need to add something or is it a bug from away3d ?

**Comment by Greg209** [comment]
It's been a while since I looked at code as I was working on a separate branch. I've just switched back to master and now experience the green textures - will now investigate.

**Comment by Greg209** [comment]
Since upgrading to Openfl 2.2.x a bug has been introduced to speed up the getRGBAPixels method. I've corrected this and issued a pull request for the core OpenFL project. Awaiting it's acceptance for this to be fixed.

**Comment by Type1J** [comment]
@Greg209 The Away3D readme.md wasn't updated with your haxelib.json change. It still says:

Dependencies

Requires OpenFL 2.0.1

NOTE: Currently the GitHub master of OpenFL is required as it contains classes which are not in the released version.

**Comment by Greg209** [comment]
Changes now to use latest (2.2.4) OpenFL/Lime and Away3d. README.markdown updated to reflect latest changes
