### ISSUE TITLE
Math.isNaN doesn't work in Drag3D.intersect()

### ISSUE THREAD

**Issue by 7ujian** [away3d/away3d-core-openfl#32]
Hi there,

I noticed a bug in the away3d-core-openfl. The default values of x, y in the private function intersect(?x:Float, ?y:Float):Void {} params are "null" instead of "NaN".

Thus the Math.isNan(x) test always fails. Changing the "Math.isNaN(x)" to "x == null" seems work.

Thank you.
Jian

**Comment by fresh-flash** [comment]
hi, I also find this bug, but solved another way. In updateDrag() function:
```
intersect(_view.mouseX, _view.mouseY);
```

**Comment by Greg209** [comment]
PR merged and new version 1.2.0 available via haxelib.
