### ISSUE TITLE
An hxcpp bug in away3d/animators/ParticleAnimationSet.hx

### ISSUE THREAD

**Issue by Type1J** [away3d/away3d-core-openfl#44]
On Haxe 3.2:
This compiles to Flash correctly, but when compiling to C++:

    away3d/animators/ParticleAnimationSet.hx:335: characters 51-59 : Local variable particle used without being initialized

I think the compiler isn't seeing line 331, which is just above this code, as an initialization:

    while (j < particlesLength && (particle = particles[j]).particleIndex == i) {
There is an assignment to particle, but the compiler just isn't happy with it.

A work around is:

    //loop through all particle data for the current particle
    while (j < particlesLength) {
        particle = particles[j];
        if (particle.particleIndex != i) {
          break;
        }
    ...

I'm guessing that this is an hxcpp bug, but it has an easy work around. I'm posting an issue for hxcpp, but until that gets fixed, this workaround may be necessary.

**Comment by Type1J** [comment]
... It looks like this is not the only place in Away3D that hxcpp has this problem. There are many other places, but similar workarounds still exist, and work correctly.

**Comment by Greg209** [comment]
Thanks for raising these issues .... Are you experiencing this on haxe 3.2? I've not tried 3.2 yet (hence the problems) and am not experiencing the same issues that I'm aware of using 3.1.3.

**Comment by Type1J** [comment]
Sorry, yes, I added "On Haxe 3.2" to the original comment, now.

**Comment by Simn** [comment]
I can take a look if someone posts a minimal reproducible example.

**Comment by Type1J** [comment]
@Simn: Here's an example:
build.hxml:

    -js AssignmentTest.js
    -main AssignmentTest
    
    --next
    
    -swf AssignmentTest.swf
    -main AssignmentTest
    
    --next
    
    -cpp AssignmentTest
    -main AssignmentTest

AssignmentTest.hx:

    class AssignmentTest {
      public static function main():Void {
        trace("Start: ");
        var i:Int;
        var b = true;
        while (b && ((i = 18) < 20)) {
          trace(" Assignment! ");
          ++i;
        }
      }
    }

An "haxe build.hxml" yields:
    AssignmentTest.hx:8: characters 8-9 : Local variable i used without being initialized

I thought that it might not happen with primitives, or that it only happens with monomorphs, but it happens with well defined primitives as well.

Changing the reference to b in the loop condition to a bool literal of true removes the error.

I really don't know if this is a "bug" or "as designed". It may be that the stricter type checking of Haxe 3.2 requires unconditional initialization before conditional use.

**Comment by Type1J** [comment]
https://github.com/openfl/openfl/blob/master/openfl/utils/AGALMiniAssembler.hx around line 283 has this error as well.

**Comment by Simn** [comment]
Fixed in Haxe.

**Comment by Type1J** [comment]
@Simn: Thanks!
@:Greg209: When you do start using Haxe 3.2, there should be no code changes necessary for this issue, so I'm closing it now.

**Comment by Greg209** [comment]
Awesome !!!!!
