### ISSUE TITLE
Can't run Basic_Shading demo

### ISSUE THREAD

**Issue by kewp** [away3d/away3d-core-openfl#49]
Just installed away3d for the first time.

`
C:\dev\away3d>haxelib list
actuate: [1.8.4]
away3d-examples: [1.1.0]
away3d: [1.1.0]
box2d: [1.2.3]
flixel-addons: [1.1.0]
flixel-demos: [1.1.1]
flixel-templates: [1.0.2]
flixel-tools: [1.0.5]
flixel-ui: [1.0.2]
flixel: [3.3.8]
hxcpp: 3.2.81 [3.2.94]
layout: [1.2.0]
lime-samples: [2.3.0]
lime: [2.3.3]
openfl-samples: [2.2.2]
openfl: [2.2.4] 3.0.3
swf: [1.8.6]
`

I'm getting (different) errors trying to run for lime, flash and html5.

`
C:\dev\away3d\Basic_Shading>lime test neko
Called from openfl/_v2/utils/ByteArray.hx line 757
Called from openfl/_v2/Lib.hx line 248
Called from openfl/_v2/Lib.hx line 391
Called from openfl/_v2/Lib.hx line 193
Called from C:\HaxeToolkit\haxe\std/neko/Lib.hx line 30
Uncaught exception - load.c(237) : Failed to load library : lime.ndll
`

`
C:\dev\away3d\Basic_Shading>lime test flash
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:157: characters 10-14 : li
me.text.Font should be openfl.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:157: characters 10-14 : li
me.text.Font should be flash.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:577: lines 577-582 : font
: openfl.text.Font -> Void should be lime.text.Font -> Void
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:577: lines 577-582 : Canno
t unify argument 1
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:577: lines 577-582 : lime.
text.Font should be openfl.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:577: lines 577-582 : lime.
text.Font should be flash.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:577: lines 577-582 : For f
unction argument 'handler'
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:586: characters 35-42 : op
enfl.text.Font -> Void should be lime.text.Font -> Void
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:586: characters 35-42 : Ca
nnot unify argument 1
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:586: characters 35-42 : li
me.text.Font should be openfl.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:586: characters 35-42 : li
me.text.Font should be flash.text.Font
C:/HaxeToolkit/haxe/lib/openfl/2,2,4/openfl/Assets.hx:586: characters 35-42 : Fo
r function argument 'handler'
`

`
C:\dev\away3d\Basic_Shading>lime test html5
Error: Could not find haxelib "format", does it need to be installed?
`

**Comment by Greg209** [comment]
Using latest OpenFL and specifying -Dlegacy fixed the issues.

http://community.openfl.org/t/away3d-basic-shader-demo-not-working/1405
