### ISSUE TITLE
View3D resize on html5 doesn't work properly

### ISSUE THREAD

**Issue by xastor** [away3d/away3d-core-openfl#53]
When you resize a View3D component by changing its width and height properties, strange things happen.  The renderer seems to track the change, but the view keeps its original size.  I tracked this down to the html canvas element not receiving a new size.  

I validated this by giving the Context3D class private access to the DisplayObject class and explicitly updating DisplayObject.__canvas.width and height on every resize.  With this change, resizing the View3D object works as expected.

Since the OpenGLView doesn't resize properly, I suppose this is an issue for OpenFL?

**Comment by Greg209** [comment]
I already have a fix for this locally but need to finish off some other edits/tests before issuing a PR to OpenFL. I'll leave this open until the fix is in. thanks

**Comment by Greg209** [comment]
This should be fixed with the latest OpenFL (released version) and Away3D (git)
