### ISSUE TITLE
failure. Type not found: A

### ISSUE THREAD

**Issue by raould** [away3d/away3d-core-openfl#55]
Ubuntu 14.04 x86 / Fresh install of everything today other than Haxe 3.2.0 that I've had on here for a couple of weeks.

Inside the Basic_View example, with no modifications (other than haxelib installing missing required libraries):

$ openfl test html5
/usr/lib/haxe/lib/away3d/1,1,0/away3d/utils/ArrayUtils.hx:76: characters 15-89 : Type not found : A

$ openfl test html5 -Dlegacy
/usr/lib/haxe/lib/away3d/1,1,0/away3d/utils/ArrayUtils.hx:76: characters 15-89 : Type not found : A

$ openfl test flash
/usr/lib/haxe/lib/away3d/1,1,0/away3d/utils/ArrayUtils.hx:76: characters 15-89 : Type not found : A

**Comment by Greg209** [comment]
Can you try the latest version from git which contains fixes for haxe 3.2.0. 

haxelib git away3d https://github.com/away3d/away3d-core-openfl.git

**Comment by raould** [comment]
Thanks for your note. I'm unlikely to have a chance to check any time soon!

**Comment by LexGear** [comment]
I'm having a similar sort of issue. I'm getting a "Type not found : Vector" error. I'm really stuck.

**Comment by modjke** [comment]
@LexGear try to clear your imports, not all of the classes are implemented fully. For example, importing Trident also improts some of the extrusions which are not yet implemented.

**Comment by TiZ-EX1** [comment]
Hi there. Haxe 3.2 has been the stable release since May, and Haxe 3.2.1 just came out. Is there anything blocking a haxelib release being made that contains this fix?
