### ISSUE TITLE
Type not found : Vector

### ISSUE THREAD

**Issue by LexGear** [away3d/away3d-core-openfl#56]
When attempting to build or test with any platform I get the "Type not found : Vector" error.

It points to the MeshHelper.hx file; line 406 to 535.

This is a fresh install of away3d / haxe / openfl.

**Comment by modjke** [comment]
Yes, there are 2 pull requests waiting for @Greg209 to merge.
This https://github.com/away3d/away3d-core-openfl/pull/60
and this https://github.com/away3d/away3d-core-openfl/pull/38

**Comment by Greg209** [comment]
PR's merged and additional changes made to fix Neko. Should now be fixed
