### ISSUE TITLE
readme error?

### ISSUE THREAD

**Issue by revilossor** [away3d/away3d-core-openfl#65]
Hi all - just tried building the basic view example, with my openfl version set to 2.2.4 ( and lime 2.6.9 ) - I was getting a load of compiler errors, with or without -Dlegacy

I set my openfl version to 3.3.9 ( and lime 2.6.9 ) and 'openfl test html5 -Dlegacy' works fine.

Does the 'Dependencies' bit of the readme need updating?

(i guess openfl-html5 could be involved too - i'm on version 1.0.5)

Thanks

**Comment by Greg209** [comment]
New version (1.2.0) now available via haxelib which uses latest OpenFL/Lime.
