### ISSUE TITLE
will neko be possible with away3d?

### ISSUE THREAD

**Issue by lewislepton** [away3d/away3d-core-openfl#69]
howdy,

this has more than likely come up. but have not seen any answer. but can away3d use neko?

it does pop up with the good ol' `Uncaught exception - std@module_read` [a bit like what nape would kick out]
so can or will away3d have a future in neko land

if so and if there is a way, whatwould be the work around?

thanks

**Comment by Greg209** [comment]
Are you using a Mac by any chance? If so, there is a known problem with neko on the Mac and the size of files it generates which causes the error - and is most annoying. I understand this was a problem on Linux but a later build was made to overcome this problem but it's not been done for the Mac - I must admit I don't fully understand the problem.

One think you can try - which won't always work, depending on your code - but you could try and utilise dead-code-elimination to reduce the generated code output.
e.g.

    openfl test neko -Ddce=full

This isn't an Away3D specific issue so closing it for now.
