### ISSUE TITLE
Cannot compile Flash, HTML5 or Windows on Haxe 3.2.1: "Normal variables cannot be accessed with 'super', use 'this' instead"

### ISSUE THREAD

**Issue by TerryCavanagh** [away3d/away3d-core-openfl#70]
I'm unable to compile the current version of away3d with haxe 3.2.1. I followed these steps:

`
haxelib git away3d https://github.com/away3d/away3d-core-openfl.git
`

(I installed from github rather than haxelib to work around https://github.com/away3d/away3d-core-openfl/issues/55. If I use the haxelib version on 3.2.1, I get the same error message as in that issue.)

I then installed the basic view example:

```
haxelib install away3d-examples
lime create away3d:Basic_View
cd Basic_View
```

On flash:

```
openfl build flash -Dlegacy
```
produces this error:

```
c:\My Stuff\Games\current\3d shit\demos\Basic_View>openfl build flash -Dlegacy
C:/coding/haxe/haxe/lib/away3d/git/away3d/events/TouchEvent3D.hx:96: characters 15-28 : Normal variables cannot be accessed with 'super', use 'this' instead
C:/coding/haxe/haxe/lib/away3d/git/away3d/events/MouseEvent3D.hx:137: characters 30-43 : Normal variables cannot be accessed with 'super', use 'this' instead
C:/coding/haxe/haxe/lib/away3d/git/away3d/containers/View3D.hx:603: characters 8-21 : Normal variables cannot be accessed with 'super', use 'this' instead
```

On HTML5:

```
openfl build html5 -Dlegacy
```

Produces this error:

```
C:/coding/haxe/haxe/lib/away3d/git/away3d/utils/Cast.hx:29: characters 25-34 : Cannot use abstract as value
```

Finally, on windows:

```
openfl build html5 -Dlegacy
```

...produces this error:

```
cl.exe -Iinclude -nologo -O2 -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Oy- -c -EHs -GS- -arch:SSE -IC:/coding/haxe/haxe/lib/hxcpp/3,2,193/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN -wd4996 -Ie:/VS8//PlatformSDK/Include -MT ./src/sys/io/FileOutput.cpp "-Foc:/My Stuff/Games/current/3dtests/demos/Basic_View/Export/windows/cpp/obj/obj/msvc-ncxp/de19829f_FileOutput.obj"
Process creation failure : cl.exe
```

(Neko worked fine, though!)

**Comment by fresh-flash** [comment]
Perhaps problem in new openfl? Try openfl 3.3.9 and lime 2.7.0

**Comment by TerryCavanagh** [comment]
Ok, I gave that a go! 

```
haxelib set openfl
Version : 3.3.9
Library openfl current version is now 3.3.9
```

So, I set openfl to 3.3.9: running the following:

```
openfl build flash -Dlegacy
```

Now gives a different error:

```
C:/coding/haxe/haxe/lib/openfl/3,3,9/openfl/utils/ByteArray.hx:5: characters 0-19 : Type not found : lime.utils.ByteArray
```

Also tried 2.2.4 for good measure, but got the same bug :(

**Comment by TerryCavanagh** [comment]
Ah! Just had a breakthrough!

I installed version 2.1.0 of lime as well, and set my lime version to that with:

`
haxelib set lime 2.1.0
`

After that I was able to compile the flash version fine. Woo!

I'm gonna

**Comment by guyvert1** [comment]
For info, I lost my haxe/lib install recently and had to redo, had very similar issues to you, but got working eventually with these lib versions 

Haxe Compiler 3.2.1 - (C)2005-2015 Haxe Foundation

actuate: [1.8.6]
away3d: git [dev:/usr/local/lib/haxelib/away3d/git]
format: [3.2.1]
hxcpp: [3.2.193]
lime: [2.8.1]
openfl: [3.5.1]

However, I can only get C++ targets to work, which is fine and not targeting flash.

**Comment by TerryCavanagh** [comment]
Ah, that's interesting - I was only targetting flash, but more long term I'm interested in C++ targets too.

Here's hoping the library gets updated to work with the latest versions of OpenFL at some point!

**Comment by Shrill** [comment]
I'll second that, I've been experimenting with Away3D OpenFL for a few months and been quite impressed, it would be great if it fully supported the latest OpenFL/Lime.

**Comment by TerryCavanagh** [comment]
Looks like Away3D just got updated to work on the latest version of OpenFL, which fixes this. Awesome!
