### ISSUE TITLE
OpenFL 4.x compatibility

### ISSUE THREAD

**Issue by StephenKDS** [away3d/away3d-core-openfl#82]
Can you please let me know when or if there is an ETA for compatibility for OpenFL 4.X. Between 3.61 and 4.0 the Display3D structure changed so it no longer works and is missing classes (i.e. will need to be adapted).

Its a shame it doesn't work anymore on OpenFL with recent versions.

**Comment by StephenKDS** [comment]
I have noticed someone has fixed this - but is awaiting a MERGE.
https://github.com/away3d/away3d-core-openfl/pull/81

**Comment by peteshand** [comment]
Hi there. I've merged. If you can give it a test and let me know if you encounter any issues that would be great.

**Comment by StephenKDS** [comment]
Awesome news! I will do soon.

Regards,
Stephen

**Comment by StephenKDS** [comment]
Are you able to push this to haxelib so I can use the normal *haxelib
upgrade* feature?

**Comment by peteshand** [comment]
1.3.2 is now available on haxelib.

**Comment by StephenKDS** [comment]
Tried the latest (Away3D 1.3.2) that was merged.

Using: OpenFL 4.0.3, Away3D 1.3.2

during iOS simulator build get these errors:
[away3d/core/managers/Stage3DProxy.hx:166]
openfl.display3D.Context3D has no field removeRenderMethod

[away3d/core/managers/Stage3DProxy.hx:174]
openfl.display3D.Context3D has no field setRenderMethod

Any ideas how to fix this?

**Comment by peteshand** [comment]
Hi Stephen

So these changes were made for OpenFL 4.0.0 or 4.0.1
Stage3D in the latest versions of OpenFL is very unstable: https://github.com/openfl/openfl/pull/1224
I'd suggest downgrading 4.0.0 or even 3.6 until we have a chance to look stabilising things. Unfortunately I'm pretty busy with other projects right now, but it's on my radar.

**Comment by StephenKDS** [comment]
It appears Away3D won't build with 4.0.0 +, and now I've switched OpenFL
back to 3.6.1, Lime is broken. Do you know which version of Lime is
supposed to be matched with OpenFL 3.6.1?

**Comment by man2** [comment]
i used the latest lime with openfl 3 github branch ( not from 3.6.1 haxelib ) is working fine

**Comment by peteshand** [comment]
OpenFL 3.6.1 and Lime 2.9 i think
