### ISSUE TITLE
Errors running 'openfl test' in all platforms

### ISSUE THREAD

**Issue by thronecode** [away3d/away3d-core-openfl#93]
`OS: Windows 7 - Ultimate 64bit`

`openfl version: 3.5.3`
`lime version: 2.9.3`

**results**: 
`C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/math/Matrix3DUtils.hx:201: characters 90-102 : Parameter default value should be constant
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/Stage3DProxy.hx:603: characters 29-53 : String should be Null<openfl.display3D.Context3DRenderMode>
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/Stage3DProxy.hx:603: characters 29-53 : String should be openfl.display3D.Context3DRenderMode
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/Stage3DProxy.hx:603: characters 29-53 : For optional function argument 'context3DRenderMode'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/render/BackgroundImageRenderer.hx:121: characters 42-54 : Too many arguments
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/render/BackgroundImageRenderer.hx:121: characters 65-92 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/render/BackgroundImageRenderer.hx:121: characters 65-92 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:96: characters 56-68 : Too many arguments
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:96: characters 79-106 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:96: characters 79-106 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:97: characters 58-70 : Too many arguments
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:97: characters 81-110 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/managers/AGALProgram3DCache.hx:97: characters 81-110 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/pick/ShaderPicker.hx:250: characters 59-86 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/pick/ShaderPicker.hx:250: characters 59-86 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/pick/ShaderPicker.hx:275: characters 61-88 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/core/pick/ShaderPicker.hx:275: characters 61-88 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/filters/tasks/Filter3DTaskBase.hx:138: characters 42-54 : Too many arguments
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/filters/tasks/Filter3DTaskBase.hx:138: characters 65-92 : openfl.display3D.Context3DProgramType should be String
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/filters/tasks/Filter3DTaskBase.hx:138: characters 65-92 : For function argument 'source'
C:/HaxeToolkit/haxe/lib/away3d/5,0,0/away3d/materials/methods/ShaderMethodSetup.hx:281: characters 2-19 : openfl.Vector<away3d.materials.methods.MethodVOSet> has no field insertAt
`

TIA guys :dagger:

**Comment by Greg209** [comment]
The current version of Away3d on haxelib is now hosted at https://github.com/openfl/away3d - this repository is now out-of-date - yes, I need to update the readme to reflect that, sorry. As such you will also need to use the recent versions of openfl (4.7+) and lime (3.7+).

These can be installed via haxelib or the openfl upgrade process. 

Also, with the latest code you shouldn't need to use the -Dlegacy flag.

If you still have issues, can you create an issue over on the openfl/away3d repo.

Thnx
